version: '3.5'

services:

  gc-php-cli:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
    - ./app:/var/www
    - composer:/root/.composer/cache

  gc-php-fpm:
    container_name: gc-php-fpm
    build:
      context: ./docker/php/fpm
      dockerfile: Dockerfile
    volumes:
    - ./app:/var/www

  gc-nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
    - ./app:/var/www
    ports:
    - "3107:80"
    depends_on:
    - gc-php-fpm

volumes:
  composer: