version: '3.5'

services:

  #  gc-php-cli:
  #    container_name: gc-php-cli
  #    build:
  #      context: ./docker/php
  #      dockerfile: Dockerfile
  #    volumes:
  #    - ./app:/var/www
  #    - composer:/root/.composer/cache

  gc-php-fpm:
    container_name: gc-php-fpm
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        ENVIRONMENT: dev
    volumes:
    - ./app:/var/www:rw
    - ~/.ssh:/root/.ssh:ro
    networks:
    - gc-network

  gc-nginx:
    container_name: gc-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        ENVIRONMENT: dev
    volumes:
    - ./app:/var/www
    networks:
    - gc-network
    ports:
    - 3107:80
    depends_on:
    - gc-php-fpm

networks:
  gc-network:
    external: true