version: '3.5'

services:

  gc-php-fpm:
    container_name: gc-php-fpm
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: dev
      args:
        ENVIRONMENT: dev
    volumes:
    - ./app:/var/www:rw
    - ~/.ssh:/root/.ssh:ro
    networks:
    - gc-network
    working_dir: /var/www

  gc-nginx:
    container_name: gc-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        ENVIRONMENT: dev
    volumes:
    - ./app:/var/www
    networks:
    - gc-network
    ports:
    - 3107:80
    depends_on:
    - gc-php-fpm

networks:
  gc-network:
    external: true