apiVersion: batch/v1
kind: Job
metadata:
  name: gc-example-job
  namespace: gc-example
spec:
  template:
    spec:
      volumes:
      - name: gc-log-storages
        persistentVolumeClaim:
          claimName: gc-example-pvc
      containers:
      - name: gc-job-example
        image: judzhin/gc-php-fpm-example:v1
        command:  ['php', 'bin/clear-config-cache.php']
        volumeMounts:
        - mountPath: "/var/www/html/data/logs"
          name: gc-log-storages
      restartPolicy: Never
  backoffLimit: 4