apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gc-example-cron
  namespace: gc-example
  labels:
    app: gc-cron-example
    type: cronjob
    chart: "gc-cron-example-v1"
spec:
  schedule: "* * * * *"
  concurrencyPolicy: 'Forbid'
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: gc-cron-example
            type: cronjob
        spec:
          volumes:
            - name: gc-log-storages
              persistentVolumeClaim:
                claimName: gc-example-pvc
          restartPolicy: Never
          containers:
            - name: gc-cron-example
              image: judzhin/gc-php-fpm-example:v1
              imagePullPolicy: Always
              command:  ['php', 'bin/process.php']
              volumeMounts:
                - mountPath: "/var/www/html/data/logs"
                  name: gc-log-storages
              env:
                - name: "POD_IP"
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP