apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  name: gc-example-svc
  namespace: gc-example
spec:
  # type: NodePort # need to remove
  selector:
    app: gc-example
    type: web-service
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 32007 # need to remove
    protocol: TCP