apiVersion: v1
kind: Service
metadata:
  name: gc-example-svc
  namespace: gc-example
spec:
  # type: NodePort
  selector:
    app: gc-example
    type: web-service
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 32007
    protocol: TCP